### PR TITLE
fix: missing react/jsx-runtime for require-hooks

### PR DESCRIPTION
**Pull request by conico974**
Should fix `Cannot find module /var/task/node_modules/react/jsx-runtime.js`

### CODE REVIEW

**Comment by revmischa** [comment]
Latest nextjs is not useable and throws this error, so any fix would be greatly appreciated

**Comment by suil** [comment]
anyone can get this resolved and merged. our prod is being broken now. please fix it. thx

**Comment by fwang** [comment]
Released in the latest version v2.0.5

**Comment by gnllucena** [comment]
how do I upgrade SST to use the latest OpenNext, @fwang?

running `npx sst deploy --stage prod` is enough to use the latest OpenNext?

**Comment by fwang** [comment]
The latest SST v2.22.1 has the latest OpenNext

**Pull request merged**
