### PR TITLE
Set `serverless-http` and `@aws-sdk/client-s3` as peerDependencies.

### PR DESCRIPTION
**Pull request by Shiroy**
These two packages are not specifically required to run open-next.

However, they are required in order for the lambda functions to be bundled correctly. Therefore, it makes sense to require them to be installed as dependencies of the Next.js application we are trying to bundle and not as dependencies of open-next itself.

This enables open-next to be used with stricter package managers such as `pnpm`.

### CODE REVIEW

**Comment by fwang** [comment]
Hey @Shiroy, I make some progress on this over the holidays. I didn't want to have the users install packages "OpenNext" uses. I will share what I have later today, just have to iron out some kinks.

**Comment by Shiroy** [comment]
My point is that package managers such as pnpm won't install open next dependencies as the application dependencies.

This prevents the lambda bundler from finding the package required by your lambda functions.

You don't have this issue with npm as everything is merged together.

Let me know if I can help you.

Best,

**Comment by fwang** [comment]
Got makes sense!

OpenNext used to move the adapters to user's app `.open-next/.build` and perform the build there, which break pnpm b/c the two dependencies won't be found as u describe.

I just published v0.4.2. It will do the build inside the OpenNext folder, and write to `.open-next/.build`. This way, it will find the dependencies.

Can you see if v0.4.2 works for ur setup?

^ Here's the pr #20

**Comment by Shiroy** [comment]
@fwang it works on my setup !

I haven't tried the result on Lambda yet, but now functions are bundled ant built correctly.

**Pull request closed without merging**
